teclado = input('Digite algo: ')
print('O tipo primitivo desse valor é',type(teclado))
print('Só tem espaços?', teclado.isspace())
print('É um numero',teclado.isnumeric())
print('é alfabetico', teclado.isalpha())
print('é alafanumerico',teclado.isalnum())
print('está e maiúsculas?', teclado.isupper())
print('está e minúsculas?', teclado.islower())
print('está capitalizada?', teclado.istitle())